output: docs/
clean: true
exclude: Tests/
author: Timofey Solomko
module: SWCompression
module_version: 4.0.0-test.1
copyright: '© 2017 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/SWCompression
github_file_prefix: https://github.com/tsolomko/SWCompression/tree/v4.0.0-test.1
theme: fullwidth

custom_categories:
    - name: Compression
      children:
      - BZip2
      - Deflate
      - LZMA
      - LZMA2
    - name: Archives
      children:
      - GzipArchive
      - GzipHeader
      - XZArchive
      - ZlibArchive
      - ZlibHeader
    - name: Containers
      children:
      - SevenZipContainer
      - SevenZipEntry
      - SevenZipEntryInfo
      - TarContainer
      - TarEntry
      - ZipContainer
      - ZipEntry
    - name: Errors
      children:
      - BZip2Error
      - DeflateError
      - LZMAError
      - LZMA2Error
      - SevenZipError
      - TarError
      - ZipError
      - GzipError
      - XZError
      - ZlibError
    - name: Protocols
      children:
      - Archive
      - Container
      - ContainerEntry
      - CompressionAlgorithm
      - DecompressionAlgorithm
