# Run: sourcekitten doc --spm --module-name SWCompression > docs.json
sourcekitten_sourcefile: docs.json
clean: false
author: Timofey Solomko
module: SWCompression
module_version: 4.8.6
copyright: '© 2024 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/SWCompression
github_file_prefix: https://github.com/tsolomko/SWCompression/tree/4.8.6
theme: fullwidth

custom_categories:
    - name: Compression
      children:
      - BZip2
      - Deflate
      - LZMA
      - LZMAProperties
      - LZMA2
      - LZ4
    - name: Archives
      children:
      - GzipArchive
      - GzipHeader
      - XZArchive
      - ZlibArchive
      - ZlibHeader
    - name: 7-Zip
      children:
      - SevenZipContainer
      - SevenZipEntry
      - SevenZipEntryInfo
    - name: TAR
      children:
      - TarContainer
      - TarReader
      - TarWriter
      - TarEntry
      - TarEntryInfo
    - name: ZIP
      children:
      - ZipContainer
      - ZipEntry
      - ZipEntryInfo
      - ZipExtraField
      - ZipExtraFieldLocation
    - name: Errors
      children:
      - BZip2Error
      - DataError
      - DeflateError
      - GzipError
      - LZMAError
      - LZMA2Error
      - SevenZipError
      - TarCreateError
      - TarError
      - XZError
      - ZipError
      - ZlibError
    - name: Protocols
      children:
      - Archive
      - Container
      - ContainerEntry
      - ContainerEntryInfo
      - CompressionAlgorithm
      - DecompressionAlgorithm
    - name: Common Auxiliary Types
      children:
      - ContainerEntryType
      - DosAttributes
      - Permissions
      - CompressionMethod
      - FileSystemType
